name: Deploy mdBook
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-crate@v1
        with:
          owner: rust-lang
          name: mdBook
      - run: mdbook build
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
